[package]
name = "project-code"
version = "0.1.0"
authors = ["wdeceuninck <wouter.deceuninck@persgroep.be>"]
edition = "2018"

[dependencies]
libc="0.2"
time="0.1"
ctrlc="3.1.1"
simple-error="0.1.13"
shuteye="0.3.3"
mmap="0.1.1"
nix="0.13.0"
rand = "0.6.5"
termion = "1.5.2"
